### ISSUE TITLE
Bean creation of unleash client stops working in spring boot 3.0.0

### ISSUE THREAD

**Issue by relnah** [Unleash/unleash-spring-boot-starter#16]
### Describe the bug

Upgrading to spring boot 3 and I get error that Unleash client bean cannot be found.

### Steps to reproduce the bug

Upgrade to spring boot 3
Start application 

### Expected behavior

Application starts and is able to find Unleash bean

### Logs, error output, etc.

```bash
Unsatisfied dependency expressed through constructor parameter 10: No qualifying bean of type 'io.getunleash.Unleash' available
```

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

1.0.25

**Comment by sjaanus** [comment]
Hey @relnah  :wave: 
Thanks for submitting this, someone from the team will get back to you on this soon.

**Comment by chriswk** [comment]
Hi @relnah. I see that we're using a deprecated way of registering our autoconfiguration classes. I'll add a PR that switches to the new method that was introduced in 2.7.x, hopefully keeping compatibility with both 2.7 and 3.0

**Comment by relnah** [comment]
Please let me know if I can help in testing.

**Comment by chriswk** [comment]
Will do. Once I get configuration properties working, I'll publish a new version so you can test

**Comment by relnah** [comment]
Hi!
How's progress? 
The Unleash starter is, unfortunately, the only dependency that is blocking us to upgrade to spring boot 3.

**Comment by praveenpg** [comment]
I get an error while trying to push a release.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:3.0.0-M7:prepare (default-cli) on project unleash-starter: Unable to commit files
[ERROR] Provider message:
[ERROR] The git-push command failed.
[ERROR] Command output:
[ERROR] ssh: Could not resolve hostname github.com:Unleash: nodename nor servname provided, or not known
[ERROR] fatal: Could not read from remote repository.
[ERROR] 
[ERROR] Please make sure you have the correct access rights
[ERROR] and the repository exists.

```
@thomasheartman Would someone more familiar with the build/release be able to get a release?

**Comment by thomasheartman** [comment]
Good question! I imagine @chriswk might know something about it ☝🏼

**Comment by chriswk** [comment]
Hi, let me give you push rights here @praveenpg.

 I tried to get a release flow working with maven and github workflow_dispatch, but couldn't get it working properly in the time I had available before Christmas.

For now I'll set you up with push rights. And I'll try to find some time to automate the process in Q2, Q1 is already booked.

**Comment by chriswk** [comment]
Hmm, you already had push rights. I'll check the scm data in the pom to make sure that its setup to the correct place and we should be able to push. 

When I think about it, we might have some problems with you pushing the maven artifact under the unleash umbrella on maven central as well.

**Comment by chriswk** [comment]
So. I've released 1.0.1 which should propagate to maven central over the next few hours. The scm urls were misconfigured which is why @praveenpg couldn't push. This is now fixed on main, so should unblock you.

I will add it to my todo list next week to have a look at access rights to maven central for releasing this package.

**Comment by chriswk** [comment]
There is a PR on this repository already upgrading to Spring 3. A workaround for you @relnah is to put a file called `org.springframework.boot.autoconfigure.AutoConfiguration.imports` into your project's `src/main/resources/META-INF/spring/` folder.

The content of this file should be
`org.unleash.features.config.UnleashAutoConfiguration`

I think that should work for triggering boot autoconfig again.

**Comment by praveenpg** [comment]
Thanks @chriswk 
I still get the following error:

```
[ERROR] Provider message:
[ERROR] The git-push command failed.
[ERROR] Command output:
[ERROR] remote: error: GH006: Protected branch update failed for refs/heads/main.        
[ERROR] remote: error: At least 1 approving review is required by reviewers with write access.        
[ERROR] To github.com:Unleash/unleash-spring-boot-starter.git
[ERROR]  ! [remote rejected] main -> main (protected branch hook declined)
[ERROR] error: failed to push some refs to 'github.com:Unleash/unleash-spring-boot-starter.git'
[ERROR] 

```
I think I might need additional permissions

**Comment by relnah** [comment]
> There is a PR on this repository already upgrading to Spring 3. A workaround for you @relnah is to put a file called `org.springframework.boot.autoconfigure.AutoConfiguration.imports` into your project's `src/main/resources/META-INF/spring/` folder.
> 
> The content of this file should be `org.unleash.features.config.UnleashAutoConfiguration`
> 
> I think that should work for triggering boot autoconfig again.

@chriswk 
That seems to work. Thanks for the temporary workaround. Hope you get the publish persmissions sorted smoothly. I'll be right here waiting to test the final fix :)

**Comment by relnah** [comment]
@chriswk Any news? Have you been able to get the release flow working and get a version working with SB 3 out?

**Comment by relnah** [comment]
I'm still waiting... :)

**Comment by sberlin** [comment]
We're blocked by this issue in trying out Unleash. I wasn't able to solve the injection of 
org.unleash.features.autoconfigure.UnleashProperties, so the configuration values get loaded successfully. We're very much interested in a fix.

**Comment by sberlin** [comment]
We solved the following error in Spring Boot 3
`Parameter 0 of method unleashContextProvider in org.springframework.samples.petclinic.PetClinicApplication required a bean of type 'org.unleash.features.autoconfigure.UnleashProperties' that could not be found.`
with
```
+++ b/backend/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
@@ -0,0 +1 @@
+org.unleash.features.autoconfigure.UnleashProperties
```
The same applied as fix in springboot-unleash-autoconfigure for a potential PR leads to
```
Parameter 0 of method unleash in org.unleash.features.config.UnleashAutoConfiguration required a single bean, but 2 were found:
        - org.unleash.features.autoconfigure.UnleashProperties: defined in null
        - io.getunleash-org.unleash.features.autoconfigure.UnleashProperties: defined in null
```
So I'll leave it as it is and maybe somebody else can create a working PR for it.

**Comment by praveenpg** [comment]
@sberlin I created a simple working springboot web app  and don't see this issue
https://github.com/praveenpg/unleash-client-demo
This uses springboot 3 and version 1.0.1 

Can you share the application.yaml (unleash config with secrets removed)

**Comment by praveenpg** [comment]
@chriswk The latest changes in master does work with springboot 3. The changes required (https://github.com/Unleash/unleash-spring-boot-starter/blob/main/springboot-unleash-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports) is already present. How can this pushed as version 1.0.2 to maven central?

**Comment by sberlin** [comment]
Please find the attached diff of the example app, that is failing for me with the error mentioned before. I'm overlooking something when wanting to add the user from the SecurityContex:
```
diff --git a/example/pom.xml b/example/pom.xml
index 36d282f..03752f1 100644
--- a/example/pom.xml
+++ b/example/pom.xml
@@ -30,7 +30,7 @@
         <dependency>
             <groupId>io.getunleash</groupId>
             <artifactId>springboot-unleash-starter</artifactId>
-            <version>1.0.0-SNAPSHOT</version>
+            <version>1.0.1</version>
         </dependency>

     </dependencies>
diff --git a/example/src/main/java/io/getunleash/UnleashApplication.java b/example/src/main/java/io/getunleash/UnleashApplication.java
index 807304a..c9cbe66 100644
--- a/example/src/main/java/io/getunleash/UnleashApplication.java
+++ b/example/src/main/java/io/getunleash/UnleashApplication.java
@@ -1,8 +1,13 @@
 package io.getunleash;

+import io.getunleash.UnleashContext;
+import io.getunleash.UnleashContextProvider;
 import org.springframework.boot.SpringApplication;
 import org.springframework.boot.autoconfigure.SpringBootApplication;
+import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
 import org.springframework.context.ConfigurableApplicationContext;
+import org.springframework.context.annotation.Bean;
+import org.unleash.features.autoconfigure.UnleashProperties;

 @SpringBootApplication
 public class UnleashApplication {
@@ -10,5 +15,16 @@ public class UnleashApplication {
         ConfigurableApplicationContext app = SpringApplication.run(UnleashApplication.class);
         System.out.println("Configured " +app.getBeanDefinitionCount() + " beans");
     }
+       @Bean
+       @ConditionalOnMissingBean
+       public UnleashContextProvider unleashContextProvider(final UnleashProperties unleashProperties) {
+               return () -> {
+                       UnleashContext.Builder builder = UnleashContext.builder();

+                       return builder
+                                       .appName(unleashProperties.getAppName())
+                                       .environment(unleashProperties.getEnvironment())
+                                       .build();
+               };
+       }
 }
```
Nonetheless I will create a PR for the typo of the YAML configuration in the readme. That did cost us some time, too.
